DROP DATABASE IF EXISTS visitors;
CREATE DATABASE visitors;

USE visitors;

CREATE TABLE successful_mentees (
	id INT NOT NULL AUTO_INCREMENT, 
	first_name VARCHAR(30) NOT NULL,
	last_name VARCHAR(30) NOT NULL,
	bio TEXT NOT NULL,
	photo VARCHAR(250) NOT NULL,
	school_logo VARCHAR(250) NOT NULL,
	PRIMARY KEY(id)
);

CREATE TABLE mentors_visits (
	id INT NOT NULL AUTO_INCREMENT,
	first_name VARCHAR(30) NOT NULL,
	last_name VARCHAR(30) NOT NULL,
	highschool VARCHAR(250) NOT NULL,
	undergrad VARCHAR(250) NOT NULL,
	grad VARCHAR(250),
	employer VARCHAR(30),
	title VARCHAR(200),
	photo VARCHAR(250),
	PRIMARY KEY(id)

);

INSERT INTO successful_mentees (first_name, last_name, bio, photo, school_logo) VALUES ('Orlson', 'Joseph', 'Born and raised in Port-au-Prince, Haiti, he is the eldes of his family. He went to middle and high school at Saint Louis de Gonzague, one of the most renowned institutions in Haiti. During middle school, he developed an interest in computers which lead him to consider computer programming after attending Education Haiti’s summer bootcamp. His last years of high school were marked by my summer programs at Stanford University, University of Notre Dame and his admittance for undergraduate studies at Princeton University. He is very athletic and has competed at the national level in track and field and volleyball.', 'https://s3.amazonaws.com/educationhaiti/orlson_joseph.png', 'https://s3.amazonaws.com/educationhaiti/princeton.png');
INSERT INTO successful_mentees (first_name, last_name, bio, photo, school_logo) VALUES ('Jose A.', 'Carl-Elie', 'Born in Haiti, he graduated last year from Institution Saint-Louis de Gonzague and now is a student at the University of Rochester. Thanks to God, his
	mentors at Education Haiti and hard work, he had the opportunity to discover the world from a bigger point of view by studying Economics and 
	Psychology with a hint of History.', 'https://s3.amazonaws.com/educationhaiti/jose_carl.png', 'https://s3.amazonaws.com/educationhaiti/uor.png');
INSERT INTO successful_mentees (first_name, last_name, bio, photo, school_logo) VALUES ('Beverlye', 'Gedéon', 'Beverlye was born and raised in Haiti. She attended College Marie Anne from 2004 to 2017, the year she graduated and the same year she was admitted to the Class of 2021 of the University of Pennsylvania. Dreaming about creating her own green company, Beverlye is interested in a major in Economics and a minor in Environmental Studies. She has also developed a passion for both music and volleyball, hobbies that she will use to bring her spark on the campus during her college journey.', 'https://s3.amazonaws.com/educationhaiti/beverlye_gedeon.png', 'https://s3.amazonaws.com/educationhaiti/upenn.png');
INSERT INTO successful_mentees (first_name, last_name, bio, photo, school_logo) VALUES ('Cedric', 'Delmy', 'Cédric was born and raised in Haiti, went to elementary school at Saint-Joseph de Petion-Ville, then he went to Institution Saint-Louis de Gonzague for middle school and high school. He graduated from high school in 2014 and was admitted to MIT for the class of 2018. He is now pursuing a bachelor in Mechanical Engineering with a possible minor in Statistics and Data Sciences. He does ballroom dancing in his free time because it\'s a great stress relief and he loves any type of physical activity.', 'https://s3.amazonaws.com/educationhaiti/cedric_delmy.png', 'https://s3.amazonaws.com/educationhaiti/mit.png');
INSERT INTO successful_mentees (first_name, last_name, bio, photo, school_logo) VALUES ('Bedjinal', 'Gondré', 'Born and raised in Haïti, Bedjinal is a student who came from a family which faced  difficulties. He attended high school at Saint-Louis de Gonzague only a few months after the earthquake of 2010. Fortunately, he continued to be a meticulous student. Thanks to his mentors and some teachers, he started with the preparation of standardized tests(TOEFL, SAT) during the academic year 2013-2014. His determination allowed him to be accepted at Berea College for class of 2021.  His chosen major is general economics. He plays soccer and practices track and field.', 'https://s3.amazonaws.com/educationhaiti/bedjinal_gondre.png', 'https://s3.amazonaws.com/educationhaiti/berea.png');
INSERT INTO successful_mentees (first_name, last_name, bio, photo, school_logo) VALUES ('Kelly', 'Jean', 'Originally from Haiti, Kelly Rubens Jean attended Jean-Marie Guilloux during five years, then the Institution Saint-Louis de Gonzague from 2010 to 2017. Surrounded by highly determined people, Kelly dreamed about studying abroad long years ago. Thanks to God and his mentors, he is a part of  the Class of 2021 of the University of Rochester. Science-minded, Kelly intends to study Mechanical Engineering and Computer Science. Also, he is passionate about drawing and ecological activities.', 'https://s3.amazonaws.com/educationhaiti/kelly_jean.png', 'https://s3.amazonaws.com/educationhaiti/uor.png');

INSERT INTO successful_mentees (first_name, last_name, bio, photo, school_logo) VALUES ('Ludgie', 'Gelin', 'Ludgie grew up in Haiti where she received both elementary and secondary education. She graduated from Institution du Sacré-Coeur where she went to school from Kindergarten to Philo (2003-2017). She was admitted to the University of Notre Dame where she intends to pursue an engineering degree with a minor in economics, hoping to put her knowledge at the service of useful purposes later on. She enjoys playing music, spending time with family and reading is among her favorite hobbies.', 'https://s3.amazonaws.com/educationhaiti/ludgie_gelin.png', 'https://s3.amazonaws.com/educationhaiti/nd.png');
INSERT INTO successful_mentees (first_name, last_name, bio, photo, school_logo) VALUES ('Kenny', 'Nelson', 'Born and raised in Haiti, Kenny Nelson is a junior pursuing a Bachelor’s degree in Computer Science. She received a full-tuition scholarship to study at Berea College alongside a work scholarship which provides her with the opportunity to gain professional experience while getting a degree. Kenny works with the Computer Science department of Berea College on the Software Development Student Projects Initiative (SPSDI). This role has allowed her not only to give back to her community, but also develop teamwork skills which has given a strong sense of confidence when working in team settings.', 'https://s3.amazonaws.com/educationhaiti/kenny_nelson.png', 'https://s3.amazonaws.com/educationhaiti/berea.png');
INSERT INTO successful_mentees (first_name, last_name, bio, photo, school_logo) VALUES ('Cressy', 'Louis', 'Born and raised in Haiti, she went to  Sainte Rose de Lima, and graduated from there. She is a sophomore, majoring in marketing, and  has  a minor in multimedia management, at Saint Leo university. She is currently doing a marketing  internship at SMARTstart incubator in Dade City.  Her goals are to work in the marketing department in an important company where she can travel for business affairs  and to create a program for homeless children in Haiti. Cressy is a cheerful person who loves writing scary stories. Her dreams is that one day one of her stories becomes a bestseller. She also likes going on adventures, try and learn new things.', 'https://s3.amazonaws.com/educationhaiti/cressy_louis.png', 'https://s3.amazonaws.com/educationhaiti/saint_leo.png');
INSERT INTO successful_mentees (first_name, last_name, bio, photo, school_logo) VALUES ('Henry', 'E. Fraçois', 'Born and raised in Haiti, Henri E. Francois received his entire classical education at Saint Louis de Gonzague. He is a member of Notre Dame’s class of 2020 and is pursuing a degree in Computer Science. Having finished his freshman year at the University, he is currently expanding his options and considering a secondary major in economics. Henri’s interests include education and healthcare.', 'https://s3.amazonaws.com/educationhaiti/henri_francois.png', 'https://s3.amazonaws.com/educationhaiti/nd.png');
INSERT INTO successful_mentees (first_name, last_name, bio, photo, school_logo) VALUES ('Medinah', 'Lafaille', 'Originally from Haiti, where she went to school at College Marie-Anne, Medinah just completed her Freshman year at the University of Massachusetts-Boston, where she is majoring in Physics and minoring in Mathematics. As many other students, she is still learning what she wants out of a career, but she knows she wants to study Environmental Engineering. She was nominated to serve as the Peer Mentor for the Engineering/Physics Freshman Success Community of her college. She is a member of Alpha Lambda Delta Society, Fields Coordinator, Site Leader and Mentor of Strong Women,Strong Girls. She also enjoys watermelon, playing with puppies, and making new friends.', 'https://s3.amazonaws.com/educationhaiti/medinah_lafaille.png', 'https://s3.amazonaws.com/educationhaiti/michigan.png');
INSERT INTO successful_mentees (first_name, last_name, bio, photo, school_logo) VALUES ('Ralph', 'Jean-Pierre', 'Born at Saint-Louis du Sud, Haiti, Ralph was raised in Port-au-Prince. He went to School at Saint Louis De Gonzague, from which he graduated in 2016. He just completed his freshman year at Saint Leo University, where he is majoring in Business Administration and management. Ralph is a Student athlete, and he especially enjoys mixing his studies with his passion for Soccer.', 'https://s3.amazonaws.com/educationhaiti/ralph_jp.png', 'https://s3.amazonaws.com/educationhaiti/saint_leo.png');
INSERT INTO successful_mentees (first_name, last_name, bio, photo, school_logo) VALUES ('Jonathan', 'Marcelin', 'Born and raised in Port-au-Prince, Haiti, Jonathan went to elementary school at Saint-Joseph, then to high School at Saint-Louis de Gonzague. He spent his freshman year at Saint Leo University studying Biomedical Sciences, to then transfer to Stony Brook University where he is majoring in Chemical and Molecular Engineering with a possible minor in Computer Science. His goal is to go to medical school. He plays almost any kind of sport during his free time, and he is a cat person.', 'https://s3.amazonaws.com/educationhaiti/jonathan_marcelin.png', 'https://s3.amazonaws.com/educationhaiti/saint_leo.png');
INSERT INTO successful_mentees (first_name, last_name, bio, photo, school_logo) VALUES ('Fabrice', 'Cotin', 'Born and raised in Port-au-Prince, Fabrice went to school at Saint-Louis de Gonzague from 1st year of elementary school until his Senior Year.He graduated from high school in 2017 and was admitted to the University of The Ozarks in Arkansas for the class of 2021.Fabrice intends to Study Computer Science with a minor in Business Administration.His goal is to gain the maximum of knowledge and come back to Help his beloved Country “HAITI”. Fabrice is a soccer lover.In his free time, he enjoys playing and watching soccer with his friends.', 'https://s3.amazonaws.com/educationhaiti/fabrice_cotin.png', 'https://s3.amazonaws.com/educationhaiti/ozarks.png');
INSERT INTO successful_mentees (first_name, last_name, bio, photo, school_logo) VALUES ('Guenaele', 'Raphael', 'Born and raised in Haiti, Guenaele who goes by Annie, attended the lnstitution Sainte Rose de Lima from first grade to thirteenth grade (philosophy). She is currently attending Saint Leo University, and majoring in Biomedical and Health Sciences with a possible minor in Math and Chemistry. Her goal is to go to medical school. Her love for reading and writing lead her to create her own blog two and a half years ago. She is a easygoing person, and is up to discover new things that can eventually increase her knowledge, and give her a better understanding of the world.', 'https://s3.amazonaws.com/educationhaiti/guenaele_raphael.png', 'https://s3.amazonaws.com/educationhaiti/saint_leo.png');
INSERT INTO successful_mentees (first_name, last_name, bio, photo, school_logo) VALUES ('Yamilee', 'Morency', 'She was born in New York, but was raised in Haiti. She went to La Petite Ecole du Cap until the 6th grade. She started secondary school at St Francois Xavier, but because of the earthquake had to move to the US where she spent two years. There she went to Sacred Heart School. She then moved back to Haiti, went back to SFX where she completed high school. Thanks to Education Haiti she was able to enroll at St John\'s University where she is studying Chemistry. She loves being involved and enjoys reading and anime.', 'https://s3.amazonaws.com/educationhaiti/yamilee_morency.png', 'https://s3.amazonaws.com/educationhaiti/st_john.png');
INSERT INTO successful_mentees (first_name, last_name, bio, photo, school_logo) VALUES ('Jean-Marie', 'Lestrade', 'Raised in Haiti, Jean-Marie J Lestrade attended the instution Saint Louis de Gonzague from first grade to terminal. He is currently studying civil engineering at the University of South Florida for which he applied in his senior year of high school with the help of his mentors from EducationHaiti. He is planning on graduating in 2019 and is interested in a minor in geology.', 'https://s3.amazonaws.com/educationhaiti/jean_lestrade.png', 'https://s3.amazonaws.com/educationhaiti/usf.png');










INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, grad, title, photo) VALUES ('Alanda', 'Alexandre', 'Institution du Sacre Coeur', 'Montclair State University', 'Montclair State University', 'Event Services Coordinator', 'https://s3.amazonaws.com/educationhaiti/alanda_alexandre.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, photo) VALUES ('Alexandre', 'Georges', 'Saint-Louis de Gonzague', 'Stony Brook University', 'https://s3.amazonaws.com/educationhaiti/alexandre_georges.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, employer, photo) VALUES ('Ben', 'Dalusma', 'Saint-Louis de Gonzague', 'Cornell University', 'Nielsen', 'https://s3.amazonaws.com/educationhaiti/benjamin_dalusma.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, grad, photo) VALUES ('Christina', 'Bastien', 'Institution du Sacré Coeur', 'Louisiana State University', 'Louisiana State University', 'https://s3.amazonaws.com/educationhaiti/christina_bastien.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, photo) VALUES ('Christine', 'A. Trouillot', 'St. Rose de Lima', 'Cornell University', 'https://s3.amazonaws.com/educationhaiti/christine_trouillot.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, grad, employer, photo) VALUES ('Corinne', 'Joachim-Sanon Symietz', 'Institution du Sacré-Coeur', 'University of Michigan', 'Wharton Business School (Upenn)', 'Askanya & Verizon', 'https://s3.amazonaws.com/educationhaiti/corinne_joachim.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, photo) VALUES ('Cressy', 'Louis', 'St Rose de Lima', 'St Leo University', 'https://s3.amazonaws.com/educationhaiti/cressy_louis.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, employer, photo) VALUES ('David', 'Marcelin', 'St Louis de Gonzage', 'Columbia University', 'P&G', 'https://s3.amazonaws.com/educationhaiti/david_marcelin.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, employer, photo) VALUES ('Deliana', 'Martinez Peña', 'CVP', 'Slippery Rock University', 'SRU', 'https://s3.amazonaws.com/educationhaiti/deliana_pena.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, employer, photo) VALUES ('Edner', 'Paul', 'College Classique de St Marc', 'MIT', 'Barclays', 'https://s3.amazonaws.com/educationhaiti/edner_paul.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, photo) VALUES ('Guenale', 'Raphael', 'St Rose de Lima', 'St Leo University', 'https://s3.amazonaws.com/educationhaiti/guenaele_raphael.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, photo) VALUES ('Henri', 'E. François', 'St Louis de Gonzage', 'University of Notre Dame', 'https://s3.amazonaws.com/educationhaiti/henri_francois.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, photo) VALUES ('Jean-Marie', 'Lestrade', 'St Louis de Gonzage', 'University of South Florida', 'https://s3.amazonaws.com/educationhaiti/jean_lestrade.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, employer, photo) VALUES ('Jean-Pierre', 'Vertil', 'St Louis de Gonzage', 'University of Notre Dame', 'Sigora Solar', 'https://s3.amazonaws.com/educationhaiti/jp_vertil.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, employer, photo) VALUES ('Jean Stephann', 'Dubois', 'St Louis de Gonzage', 'Syracuse University', 'Avenues: The World School & EMO-HAITI', 'https://s3.amazonaws.com/educationhaiti/stephann_dubois.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, employer, photo) VALUES ('Jeffry', 'Magloire', 'Collège St Joseph', 'University of Rochester', 'Johnson Controls', 'https://s3.amazonaws.com/educationhaiti/jeffry_magloire.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, photo) VALUES ('Jonathan', 'Marcelin', 'St Louis de Gonzage', 'Stony Brook', 'https://s3.amazonaws.com/educationhaiti/jonathan_marcelin.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, grad, employer, title, photo) VALUES ('Jules', 'Walter', 'St Louis de Gonzage', 'MIT', 'Harvard', 'Slack', 'Senior Product Manager', 'https://s3.amazonaws.com/educationhaiti/jules_walter.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, grad, photo) VALUES ('Jonathan', 'Laguerre', 'St Louis de Gonzage', 'Stony Brook University', 'Wharton Business School (Upenn)', 'https://s3.amazonaws.com/educationhaiti/jonathan_laguerre.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, photo) VALUES ('Keisha', 'Target', 'St Rose de Lima', 'Cornell University', 'https://s3.amazonaws.com/educationhaiti/keisha_target.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, employer, photo) VALUES ('Kenny', 'Nelson', 'CCF', 'Berea College', 'https://s3.amazonaws.com/educationhaiti/kenny_nelson.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, grad, employer, photo) VALUES ('Manfred', 'Magloire', 'College St Joseph du Cap', 'SUNY-ESF', 'Manhattan College', 'NYSDEC', 'https://s3.amazonaws.com/educationhaiti/manfred_magloire.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, photo) VALUES ('Mat', 'Pierre', 'Institution du Sacré-Coeur', 'Pace University', 'https://s3.amazonaws.com/educationhaiti/mat_pierre.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, photo) VALUES ('Medinah', 'Lafaille', 'CMA', 'University of Massachusetts-B', 'https://s3.amazonaws.com/educationhaiti/medinah_lafaille.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, employer, photo) VALUES ('Michelle Samantha', 'Salomon', 'Institution du Sacré-Coeur', 'Illinois State University', 'Maui Jim', 'https://s3.amazonaws.com/educationhaiti/michelle_salomon.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, photo) VALUES ('Stécie', 'Norcéide', 'St François Xavier', 'TRCC', 'https://s3.amazonaws.com/educationhaiti/stecie_norceide.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, photo) VALUES ('Olivier', 'Gabriel', 'St Louis de Gonzage', 'Massoit CC', 'https://s3.amazonaws.com/educationhaiti/olivier_gabriel.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, employer, photo) VALUES ('Pascal', 'Bastien', 'St Louis de Gonzage', 'Syracuse University', 'IBM', 'https://s3.amazonaws.com/educationhaiti/pascal_bastien.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, photo) VALUES ('Ralph', 'Jean-Pierre', 'St Louis de Gonzage', 'St Leo University', 'https://s3.amazonaws.com/educationhaiti/ralph_jp.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, employer, photo) VALUES ('Romie', 'Desrogène', 'St Rose de Lima', 'Princeton', 'JP Morgan Chase & Co', 'https://s3.amazonaws.com/educationhaiti/romie_desrogene.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, grad, employer, photo) VALUES ('Sarah', 'Nerette', 'Union School', 'University of Virginia', 'American University', 'Sigora Solar', 'https://s3.amazonaws.com/educationhaiti/sarah_nerette.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, employer, photo) VALUES ('Websly', 'Darbouze', 'St Louis de Gonzague', 'Rochester Institute of Technology', 'Bergmann Associates', 'https://s3.amazonaws.com/educationhaiti/websly_darbouze.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, photo) VALUES ('Yamilee', 'Morency', 'SFX', 'St John\'s University',  'https://s3.amazonaws.com/educationhaiti/yamilee_morency.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, employer, photo) VALUES ('Chirstina', 'Beauboeuf', 'St Rose de Lima', 'Virginia Polytechnic Institute of Technology', 'CDM Smith', 'https://s3.amazonaws.com/educationhaiti/christina_beauboeuf.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, employer, photo) VALUES ('Larissa', 'Senatus', 'St Rose de Lima', 'MIT', 'Keurig Green Mountain', 'https://s3.amazonaws.com/educationhaiti/larissa_senatus.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, employer, photo) VALUES ('Jury', 'Paul', 'Petit Seminaire', 'Florida State University', 'Amica Mutual Insurance', 'https://s3.amazonaws.com/educationhaiti/jurry_paul.png');
INSERT INTO mentors_visits (first_name, last_name, highschool, undergrad, grad, employer, photo) VALUES ('Stéphane', 'Laroche', 'St Louis de Gonzage', 'Concordia College', 'Tufts University (Fletcher)', 'USAID FSO', 'https://s3.amazonaws.com/educationhaiti/stephane_laroche.png');







